export const LOAD_ITEMS = 'LOAD_ITEMS';
export const LOAD_ITEM = 'LOAD_ITEM';
export const LOAD_ITEMS_REQUEST = 'LOAD_ITEMS_REQUEST';
export const LOAD_ITEMS_SUCCESS = 'LOAD_ITEMS_SUCCESS';
export const LOAD_ITEMS_FAILURE = 'LOAD_ITEMS_FAILURE';
export const UPDATE_BOOKS_FILTER_PHRASE = 'UPDATE_BOOKS_FILTER_PHRASE';
